site_name: Heroes of Word
#site_url: https://mydomain.org/mysite
site_url: https://batyrbekcherushev.github.io/beetroot_project/
repo_url: https://github.com/BatyrbekCherushev/beetroot_project

nav:
- ІНТРО: index.md
- Документація проекта:
  - Заливка проекту на PYTHONANYWHERE: DOCUMENTATION/pythonanywhere_setup.md
  - АДМІНКА ПРОЕКТУ: DOCUMENTATION/admin.md
  - МОДЕЛІ: DOCUMENTATION/models.md
  - VOCABULARIES: DOCUMENTATION/vocabularies.md
  - FRONTEND: DOCUMENTATION/frontend.md
  - Pages: DOCUMENTATION/pages.md
  - GAME: DOCUMENTATION/game.md
  - MINI-GAMES: DOCUMENTATION/mini_games.md
  - Ideas: DOCUMENTATION/ideas.md
- Команди: 
  - DJANGO: COMMANDS/commands_django.md
  - MKDOCS: COMMANDS/commands_mkdocs.md


theme:
  name: material
  language: uk
  features:
    - search.highlight
    - navigation.footer
    - navigation.instant # ускорение загрузки (SPA)
    - navigation.tracking # динамический URL страницы 
    - navigation.tabs # перенос названий документов в горизонтальное меню
    - navigation.tabs.sticky # горизонтальное меню не скрывается при прокрутке
    - navigation.indexes # главные страницы разделов не отображаются в меню
    - navigation.top # вкл. кнопку возврата наверх
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Темний
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Світлий